stages:
  - deploy

deploy_to_lightsail:
  stage: deploy
  image: ruby:3.1
  only:
    - main
  script:
    - apt-get update -y && apt-get install -y openssh-client git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
    - |
      ssh $REMOTE_USER@$REMOTE_HOST <<EOF
      set -e
      rm -rf ~/erp_project
      git clone https://gitlab.com/Ziyoxon-2005/ERP_SYSTEM.git ~/erp_project
      cd ~/erp_project
      docker-compose down || true
      docker-compose up -d --build
      docker image prune -f
      EOF
