stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "tcp://$REMOTE_HOST:2376"
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "$CI_PROJECT_DIR/certs"

before_script:
  - apk add --no-cache openssh # Alpine image bo'lsa
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - echo "Build bosqichi o'tkazilmoqda..."
    - docker-compose build

deploy:
  stage: deploy
  script:
    - echo "Deploy bosqichi ishlamoqda..."
    - scp docker-compose.yml $REMOTE_USER@$REMOTE_HOST:/home/$REMOTE_USER/app/
    - ssh $REMOTE_USER@$REMOTE_HOST << EOF
        cd /home/$REMOTE_USER/app/
        docker-compose down
        docker-compose up -d --build
      EOF
